TARGET := iphone:clang:latest:14.0
ARCHS = arm64 arm64e

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = KeyLoader

# تأكد أن اسم الملف هنا يطابق اسم ملف الكود عندك (سواء Tweak.xm أو Tweak.x)
KeyLoader_FILES = Tweak.xm

# هنا التعديل السحري: أمرنا النظام بتجاهل تحذيرات الأكواد القديمة
KeyLoader_CFLAGS = -fobjc-arc -Wno-deprecated-declarations -Wno-error
KeyLoader_FRAMEWORKS = UIKit Foundation

include $(THEOS_MAKE_PATH)/tweak.mk
